# uvr project environment — source this file to activate:
#
#     source .uvr/activate.fish
#
# Generated by uvr; do not edit. Contains no paths: the environment is
# recomputed by the uvr binary on every activation.
if not command -q uvr
    echo "uvr: not found on PATH — cannot activate this project." >&2
else
    # Only eval on success, so a failed resolve leaves the shell untouched.
    set -l __uvr_activate_out (uvr activate --emit fish | string collect)
    if test $status -eq 0
        eval $__uvr_activate_out
    end
end
