{
  "hash": "8b8f3d9d6a5b788f5da7eb219f7a0bfd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chapter 1 · My EDA project\"\nauthor: \"Yi Qian\"\nformat: html\ndate: today\n---\n\n> **How to fill this chapter in**\n> This is your main portfolio piece. The numbered sections below follow the\n> **IMRAD** structure of research: question ≈ *introduction*, getting the\n> data + cleaning decisions ≈ *methods*, plotting the story ≈ *results*, and\n> findings ≈ *discussion*. In the *Reproducible Workflows* course:\n>\n> - **Session 2** lab: find a dataset you care about on an open-data portal\n>   (data.gouv.fr or your own country's), source it **reproducibly by code**,\n>   run an EDA, clean the data, and commit it to git.\n> - **Session 3** work block: finish and polish the chapter, pin your data and\n>   environment, open a pull request for review, and publish the book to a URL.\n>\n> Everything between the `TODO` markers below is a template to replace with\n> your own content.\n\n## The question\n\nwhat is the dominant factor to effect the potential of photovoltaic power generation?\n\n\n## Getting the data\n\nThe data is sourced **by code** from an open-data portal of your choice. Because\nthe download lives inside the document, it is recorded in the analysis itself;\nanyone who re-renders this document gets the same data and the same results.\nRecord the dataset's **publisher and URL** in the text so the provenance is\nexplicit.\n\nThe only portal-specific part is the *fetch*. This template shows two ways;\nuse the one that fits your portal:\n\n- **`{rdatagouv}`** (data.gouv.fr only, optional): search/download from R.\n- **Any portal by URL**: `download.file()` works with any portal's direct\n  download link.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"rdatagouv\")\ninstall.packages(\"janitor\")\ninstall.packages(\"pheatmap\")\nlibrary(rdatagouv)\nlibrary(janitor)\nlibrary(Factoshiny)\ninstall.packages(\"pins\")\n\nlibrary(pins)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist1<-rdatagouv::dg_find_datasets(q = \"climat\", schema_only = TRUE) \n\nlist1$id\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"64cbb61ddb9ea74936fa9b26\" \"64d6777d9295aa9ef4b04095\"\n [3] \"61b89b81fa74b1c73f4f8065\" \"6818bce2d9af175f6e01a1b2\"\n [5] \"5eeae71835cd2e8a524fc1c2\" \"66f12c1ff6d924e7e499798a\"\n [7] \"5970c5a6c751df4c451097fe\" \"6883cd2b5196629da0088505\"\n [9] \"699cecfff538ccdd0cf1e1b1\" \"678541d6780940a9f5ba5909\"\n[11] \"6aad0f707f3d039dc8b57730\" \"698df052b66e138bb93b9eb1\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndat<-rdatagouv::dg_pull_dataset(\"6883cd2b5196629da0088505\")\n\n\n\n#board <- board_folder(\"pins/\", versioned = TRUE)\n#df <- pin_read(board, \"my-data\")\n```\n:::\n\n\n> **Optionally pin the fetched copy** with `{pins}` so the chapter reads from a\n> versioned local board instead of hitting the network on every render:\n>\n\n::: {.cell}\n\n```{.r .cell-code}\nboard <- pins::board_folder(\"pins/\", versioned = TRUE)\npins::pin_write(board, dat, \"my-data\", type = \"csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n! The hash of pin \"my-data\" has not changed.\n• Your pin will not be stored.\n```\n\n\n:::\n\n```{.r .cell-code}\ndf  <- pins::pin_read(board, \"my-data\")\n```\n:::\n\n\n\n## A first look and Cleaning\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  code_insee  commune code_postal code_departement             region\n1      33063 Bordeaux       33000               33 Nouvelle-Aquitaine\n2      33063 Bordeaux       33100               33 Nouvelle-Aquitaine\n3      33063 Bordeaux       33200               33 Nouvelle-Aquitaine\n4      33063 Bordeaux       33300               33 Nouvelle-Aquitaine\n5      33063 Bordeaux       33800               33 Nouvelle-Aquitaine\n6      75115 Paris 15       75015               75      Île-de-France\n  departement      lat        lon irradiation irradiation_q1_kwhm2\n1     Gironde 44.85724 -0.5736968        1389                  218\n2     Gironde 44.85724 -0.5736968        1389                  218\n3     Gironde 44.85724 -0.5736968        1389                  218\n4     Gironde 44.85724 -0.5736968        1389                  218\n5     Gironde 44.85724 -0.5736968        1389                  218\n6       Paris 48.84016  2.2935594        1222                  172\n  irradiation_q2_kwhm2 irradiation_q3_kwhm2 irradiation_q4_kwhm2 sun_hours_q1_h\n1                  495                  498                  179         300.38\n2                  495                  498                  179         300.38\n3                  495                  498                  179         300.38\n4                  495                  498                  179         300.38\n5                  495                  498                  179         300.38\n6                  473                  444                  133         264.34\n  sun_hours_q2_h sun_hours_q3_h sun_hours_q4_h avg_temperature_q1_c\n1         565.89         530.68         259.88                 7.61\n2         565.89         530.68         259.88                 7.61\n3         565.89         530.68         259.88                 7.61\n4         565.89         530.68         259.88                 7.61\n5         565.89         530.68         259.88                 7.61\n6         527.79         492.59         222.71                 5.41\n  avg_temperature_q2_c avg_temperature_q3_c avg_temperature_q4_c\n1                16.16                20.82                10.83\n2                16.16                20.82                10.83\n3                16.16                20.82                10.83\n4                16.16                20.82                10.83\n5                16.16                20.82                10.83\n6                14.35                18.68                 8.61\n  surface_exploitable potentiel_kwh economie co2_evite_kg_an roi_annees\n1                  36          6667     1301         366.696        6.1\n2                  36          6667     1301         366.696        6.1\n3                  36          6667     1301         366.696        6.1\n4                  36          6667     1301         366.696        6.1\n5                  36          6667     1301         366.696        6.1\n6                  36          5866     1145         322.608        7.0\n  population    climat ensoleillement_annuel temperature_moyenne\n1     261804 Océanique                  1657               13.88\n2     261804 Océanique                  1657               13.88\n3     261804 Océanique                  1657               13.88\n4     261804 Océanique                  1657               13.88\n5     261804 Océanique                  1657               13.88\n6     227746   Tempéré                  1507               11.79\n                                                            fiche_url\n1 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n2 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n3 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n4 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n5 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n6        https://solairesimple.fr/region/ile-de-france/paris/paris-15\n```\n\n\n:::\n\n```{.r .cell-code}\ndf |> \n  skimr::skim() |> \n  summary()\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |df    |\n|Number of rows           |11769 |\n|Number of columns        |31    |\n|_______________________  |      |\n|Column type frequency:   |      |\n|character                |7     |\n|numeric                  |24    |\n|________________________ |      |\n|Group variables          |None  |\n\nA one-line summary of the dataset.\n:::\n\n```{.r .cell-code}\nnaniar::gg_miss_var(df)\n```\n\n::: {.cell-output-display}\n![A one-line summary of the dataset.](01-EDA_files/figure-html/skim-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndf |> tidyr::drop_na()|> head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  code_insee  commune code_postal code_departement             region\n1      33063 Bordeaux       33000               33 Nouvelle-Aquitaine\n2      33063 Bordeaux       33100               33 Nouvelle-Aquitaine\n3      33063 Bordeaux       33200               33 Nouvelle-Aquitaine\n4      33063 Bordeaux       33300               33 Nouvelle-Aquitaine\n5      33063 Bordeaux       33800               33 Nouvelle-Aquitaine\n  departement      lat        lon irradiation irradiation_q1_kwhm2\n1     Gironde 44.85724 -0.5736968        1389                  218\n2     Gironde 44.85724 -0.5736968        1389                  218\n3     Gironde 44.85724 -0.5736968        1389                  218\n4     Gironde 44.85724 -0.5736968        1389                  218\n5     Gironde 44.85724 -0.5736968        1389                  218\n  irradiation_q2_kwhm2 irradiation_q3_kwhm2 irradiation_q4_kwhm2 sun_hours_q1_h\n1                  495                  498                  179         300.38\n2                  495                  498                  179         300.38\n3                  495                  498                  179         300.38\n4                  495                  498                  179         300.38\n5                  495                  498                  179         300.38\n  sun_hours_q2_h sun_hours_q3_h sun_hours_q4_h avg_temperature_q1_c\n1         565.89         530.68         259.88                 7.61\n2         565.89         530.68         259.88                 7.61\n3         565.89         530.68         259.88                 7.61\n4         565.89         530.68         259.88                 7.61\n5         565.89         530.68         259.88                 7.61\n  avg_temperature_q2_c avg_temperature_q3_c avg_temperature_q4_c\n1                16.16                20.82                10.83\n2                16.16                20.82                10.83\n3                16.16                20.82                10.83\n4                16.16                20.82                10.83\n5                16.16                20.82                10.83\n  surface_exploitable potentiel_kwh economie co2_evite_kg_an roi_annees\n1                  36          6667     1301         366.696        6.1\n2                  36          6667     1301         366.696        6.1\n3                  36          6667     1301         366.696        6.1\n4                  36          6667     1301         366.696        6.1\n5                  36          6667     1301         366.696        6.1\n  population    climat ensoleillement_annuel temperature_moyenne\n1     261804 Océanique                  1657               13.88\n2     261804 Océanique                  1657               13.88\n3     261804 Océanique                  1657               13.88\n4     261804 Océanique                  1657               13.88\n5     261804 Océanique                  1657               13.88\n                                                            fiche_url\n1 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n2 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n3 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n4 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n5 https://solairesimple.fr/region/nouvelle-aquitaine/gironde/bordeaux\n```\n\n\n:::\n\n```{.r .cell-code}\ncolnames(df)<-df |> clean_names() |> names()\n\ndf|> tabyl(region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     region    n     percent\n       Auvergne-Rhône-Alpes 1855 0.157617470\n    Bourgogne-Franche-Comté  847 0.071968731\n                   Bretagne  426 0.036196788\n        Centre-Val de Loire  606 0.051491206\n                      Corse  229 0.019457898\n                  Grand Est 1098 0.093295947\n                 Guadeloupe   66 0.005607953\n                     Guyane   25 0.002124225\n            Hauts-de-France 1241 0.105446512\n                 La Réunion   85 0.007222364\n                 Martinique   86 0.007307333\n                    Mayotte   21 0.001784349\n                  Normandie  598 0.050811454\n         Nouvelle-Aquitaine 1247 0.105956326\n                  Occitanie 1358 0.115387883\n           Pays de la Loire  583 0.049536919\n Provence-Alpes-Côte d'Azur  827 0.070269352\n              Île-de-France  571 0.048517291\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11769    31\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\ndf<-df|>mutate(sun_hours_sum=sun_hours_q1_h+sun_hours_q2_h+sun_hours_q3_h+sun_hours_q4_h)\ndf<-df|>mutate(avg_temp=avg_temperature_q1_c+avg_temperature_q2_c+avg_temperature_q3_c+avg_temperature_q4_c)\n\n\n\ncolSums(is.na(df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           code_insee               commune           code_postal \n                    0                     0                     0 \n     code_departement                region           departement \n                    0                     0                     0 \n                  lat                   lon           irradiation \n                    0                     0                     0 \n irradiation_q1_kwhm2  irradiation_q2_kwhm2  irradiation_q3_kwhm2 \n                    0                     0                     0 \n irradiation_q4_kwhm2        sun_hours_q1_h        sun_hours_q2_h \n                    0                     0                     0 \n       sun_hours_q3_h        sun_hours_q4_h  avg_temperature_q1_c \n                    0                     0                     0 \n avg_temperature_q2_c  avg_temperature_q3_c  avg_temperature_q4_c \n                    0                     0                     0 \n  surface_exploitable         potentiel_kwh              economie \n                    0                     0                     0 \n      co2_evite_kg_an            roi_annees            population \n                    0                     0                     0 \n               climat ensoleillement_annuel   temperature_moyenne \n                    0                     0                     0 \n            fiche_url         sun_hours_sum              avg_temp \n                    0                     0                     0 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Plotting the story\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(df, aes(x = sun_hours_sum, y = potentiel_kwh, color = region)) +\n  geom_point(size = 1) +\n  labs(title = \"Sun hours vs Solar production potential\",\n       x = \"Sun hours\", y = \"Potentiel (kWh)\")+\n  theme(legend.position = \"bottom\")\n\nggplot(df, aes(x = avg_temp, y = potentiel_kwh, color = region)) +\n  geom_point(size = 1) +\n  labs(title = \"average temperature vs Solar production potential\",\n       x = \"average temperature\", y = \"Potentiel (kWh)\")+\n  theme(legend.position = \"bottom\")\n\n\nggplot(df, aes(x = region, y = irradiation, fill = climat)) +geom_boxplot(notch = FALSE,\n    outlier.color = \"purple\",\n    outlier.shape = 8,\n    outlier.size = 2,\n    alpha = 0.7)+\n  labs(title = \"Irradiation distribution\",\n       x = \"Region\",\n       y = \"Irradiation\") +\n  theme_minimal()\n\n\n\nlibrary(pheatmap)\n\n\nnum_df <- df[, sapply(df, is.numeric)]\nnum_df <- num_df[, apply(num_df, 2, function(x) sd(x, na.rm = TRUE) != 0)]\nnum_df<-num_df[,c(2,3,4,17,18,19,20,21,22,23,24,25)]\n\n\n\ncor_mat <- cor(num_df, use = \"pairwise.complete.obs\")\n\n\n\npheatmap(cor_mat,\n         cluster_rows = TRUE,\n         cluster_cols = TRUE,\n         display_numbers = TRUE,\n         number_format = \"%.2f\",\n         color = colorRampPalette(c(\"navy\", \"white\", \"firebrick3\"))(50),\n         main = \"Correlation Heatmap\")\n```\n\n::: {.cell-output-display}\n![The central figure of your analysis.](01-EDA_files/figure-html/fig-main-1.png){#fig-main-1 width=672}\n:::\n\n::: {.cell-output-display}\n![The central figure of your analysis.](01-EDA_files/figure-html/fig-main-2.png){#fig-main-2 width=672}\n:::\n\n::: {.cell-output-display}\n![The central figure of your analysis.](01-EDA_files/figure-html/fig-main-3.png){#fig-main-3 width=672}\n:::\n\n::: {.cell-output-display}\n![The central figure of your analysis.](01-EDA_files/figure-html/fig-main-4.png){#fig-main-4 width=672}\n:::\n:::\n\n\n\n## Findings\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#pca\nsapply(df, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           code_insee               commune           code_postal \n          \"character\"           \"character\"             \"integer\" \n     code_departement                region           departement \n          \"character\"           \"character\"           \"character\" \n                  lat                   lon           irradiation \n            \"numeric\"             \"numeric\"             \"integer\" \n irradiation_q1_kwhm2  irradiation_q2_kwhm2  irradiation_q3_kwhm2 \n            \"integer\"             \"integer\"             \"integer\" \n irradiation_q4_kwhm2        sun_hours_q1_h        sun_hours_q2_h \n            \"integer\"             \"numeric\"             \"numeric\" \n       sun_hours_q3_h        sun_hours_q4_h  avg_temperature_q1_c \n            \"numeric\"             \"numeric\"             \"numeric\" \n avg_temperature_q2_c  avg_temperature_q3_c  avg_temperature_q4_c \n            \"numeric\"             \"numeric\"             \"numeric\" \n  surface_exploitable         potentiel_kwh              economie \n            \"integer\"             \"integer\"             \"integer\" \n      co2_evite_kg_an            roi_annees            population \n            \"numeric\"             \"numeric\"             \"integer\" \n               climat ensoleillement_annuel   temperature_moyenne \n          \"character\"             \"integer\"             \"numeric\" \n            fiche_url         sun_hours_sum              avg_temp \n          \"character\"             \"numeric\"             \"numeric\" \n```\n\n\n:::\n\n```{.r .cell-code}\n#non_char_df <- df[,!sapply(df, is.character)]\n#col_variances <- sapply(non_char_df, var,na.rm=TRUE)\n#dynamic_cols <-  col_variances > 0 & !is.na(col_variances)\n#dfprep<-non_char_df[,dynamic_cols]\n#colnames(dfprep)\n\n#PCAshiny(dfprep)\n#res.PCA<-PCA(dfprep,quali.sup=c(1,5,6,7,8,9,10,11,12,13,14,15,16),graph=FALSE)\n#plot.PCA(res.PCA,choix='var')\n#plot.PCA(res.PCA)\n\n#what is the dominant factor to effect the potential of photovoltaic power generation?\n\ncolnames(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"code_insee\"            \"commune\"               \"code_postal\"          \n [4] \"code_departement\"      \"region\"                \"departement\"          \n [7] \"lat\"                   \"lon\"                   \"irradiation\"          \n[10] \"irradiation_q1_kwhm2\"  \"irradiation_q2_kwhm2\"  \"irradiation_q3_kwhm2\" \n[13] \"irradiation_q4_kwhm2\"  \"sun_hours_q1_h\"        \"sun_hours_q2_h\"       \n[16] \"sun_hours_q3_h\"        \"sun_hours_q4_h\"        \"avg_temperature_q1_c\" \n[19] \"avg_temperature_q2_c\"  \"avg_temperature_q3_c\"  \"avg_temperature_q4_c\" \n[22] \"surface_exploitable\"   \"potentiel_kwh\"         \"economie\"             \n[25] \"co2_evite_kg_an\"       \"roi_annees\"            \"population\"           \n[28] \"climat\"                \"ensoleillement_annuel\" \"temperature_moyenne\"  \n[31] \"fiche_url\"             \"sun_hours_sum\"         \"avg_temp\"             \n```\n\n\n:::\n\n```{.r .cell-code}\n#climate_vars <- c(\"temperature_moyenne\", \"ensoleillement_annuel\",\"irradiation\", \"sun_hours_sum\",\"climat\")\n#geo_vars <- c(\"lat\", \"lon\", \"population\",\"region\")\n#outcome_var <- \"potential_kwh\"  \n#benefit_vars <- c(\"co2_evite_kg_an\", \"economie\",\"roi_annees\")  \n\npca_vars <- c(\"temperature_moyenne\", \"irradiation\",\n              \"lat\", \"lon\", \"population\")\nsupp_vars <- c(\"potentiel_kwh\", \"co2_evite_kg_an\", \"economie\")\n\nall_df <- df[, c(pca_vars, supp_vars)]\nall_df <- all_df[, apply(all_df, 2, function(x) sd(x, na.rm = TRUE) != 0)]\nall_df <- na.omit(all_df)\n\n\npca_res <- PCA(all_df,\n               scale.unit = TRUE,\n               ncp = 5,\n               graph = FALSE,\n               quanti.sup = which(colnames(all_df) %in% supp_vars))\n\nsummary(pca_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nPCA(X = all_df, scale.unit = TRUE, ncp = 5, quanti.sup = which(colnames(all_df) %in%  \n     supp_vars), graph = FALSE) \n\n\nEigenvalues\n                       Dim.1   Dim.2   Dim.3   Dim.4   Dim.5\nVariance               2.409   1.065   0.955   0.338   0.233\n% of var.             48.171  21.302  19.107   6.752   4.668\nCumulative % of var.  48.171  69.473  88.580  95.332 100.000\n\nIndividuals (the 10 first)\n                        Dist    Dim.1    ctr   cos2    Dim.2    ctr   cos2  \n1                   | 21.798 |  1.959  0.014  0.008 | 13.923  1.546  0.408 |\n2                   | 21.798 |  1.959  0.014  0.008 | 13.923  1.546  0.408 |\n3                   | 21.798 |  1.959  0.014  0.008 | 13.923  1.546  0.408 |\n4                   | 21.798 |  1.959  0.014  0.008 | 13.923  1.546  0.408 |\n5                   | 21.798 |  1.959  0.014  0.008 | 13.923  1.546  0.408 |\n6                   | 18.930 |  0.410  0.001  0.000 | 12.158  1.179  0.412 |\n7                   | 15.749 |  0.191  0.000  0.000 | 10.154  0.823  0.416 |\n8                   | 15.631 |  0.238  0.000  0.000 | 10.079  0.810  0.416 |\n9                   | 15.059 |  0.186  0.000  0.000 |  9.718  0.753  0.416 |\n10                  | 14.784 |  0.187  0.000  0.000 |  9.542  0.726  0.417 |\n                     Dim.3    ctr   cos2  \n1                   16.627  2.459  0.582 |\n2                   16.627  2.459  0.582 |\n3                   16.627  2.459  0.582 |\n4                   16.627  2.459  0.582 |\n5                   16.627  2.459  0.582 |\n6                   14.472  1.863  0.584 |\n7                   12.010  1.283  0.582 |\n8                   11.921  1.264  0.582 |\n9                   11.479  1.172  0.581 |\n10                  11.268  1.129  0.581 |\n\nVariables\n                       Dim.1    ctr   cos2    Dim.2    ctr   cos2    Dim.3\ntemperature_moyenne |  0.894 33.168  0.799 |  0.091  0.785  0.008 | -0.048\nirradiation         |  0.877 31.930  0.769 | -0.105  1.039  0.011 |  0.037\nlat                 | -0.817 27.740  0.668 |  0.393 14.474  0.154 | -0.225\nlon                 | -0.407  6.890  0.166 | -0.685 44.005  0.469 |  0.576\npopulation          |  0.081  0.271  0.007 |  0.650 39.697  0.423 |  0.755\n                       ctr   cos2  \ntemperature_moyenne  0.240  0.002 |\nirradiation          0.142  0.001 |\nlat                  5.305  0.051 |\nlon                 34.689  0.331 |\npopulation          59.625  0.570 |\n\nSupplementary continuous variables\n                       Dim.1   cos2    Dim.2   cos2    Dim.3   cos2  \npotentiel_kwh       |  0.877  0.769 | -0.105  0.011 |  0.037  0.001 |\nco2_evite_kg_an     |  0.877  0.769 | -0.105  0.011 |  0.037  0.001 |\neconomie            |  0.877  0.769 | -0.105  0.011 |  0.037  0.001 |\n```\n\n\n:::\n\n```{.r .cell-code}\nround(pca_res$quanti.sup$cor[, 1:3], 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Dim.1 Dim.2 Dim.3\npotentiel_kwh    0.88 -0.11  0.04\nco2_evite_kg_an  0.88 -0.11  0.04\neconomie         0.88 -0.11  0.04\n```\n\n\n:::\n:::\n\n---\n\n*The dominant factors for photovoltaic power generation potential are temperature and irradiation. Dim.1 explains 48.2% of the variance, while temperature (loading 0.894)and radiation (loading 0.877) drives positively and the latitude (loading -0.817) drives negatively.The correlation coefficient between potentiel_kwh and Dim.1 is 0.88 which means the potentiel_kwh is determined by Dim.1. So the key point to improve potentiel_kwh is the temperature and irradation, and the region in high latitude has lower potential.*\n\n[@wickham2019r4ds]\n\n## References\n\n",
    "supporting": [
      "01-EDA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}