# uvr project environment — dot-source this file to activate:
#
#     . .uvr/activate.ps1
#
# Generated by uvr; do not edit. Contains no paths: the environment is
# recomputed by the uvr binary on every activation.
if (-not (Get-Command uvr -ErrorAction SilentlyContinue)) {
    Write-Error "uvr: not found on PATH — cannot activate this project."
} else {
    # Only invoke on success, so a failed resolve leaves the shell untouched.
    $uvrActivateOut = & uvr activate --emit powershell
    if ($LASTEXITCODE -eq 0) {
        Invoke-Expression ($uvrActivateOut -join "`n")
    }
}
